name-template: v$RESOLVED_VERSION ️⚡️
tag-template: v$RESOLVED_VERSION
exclude-contributors:
  - github-actions[bot]
  - github-actions
  - dependabot[bot]
  - dependabot
categories:
  - title: ❗️ Breaking Changes
    labels:
      - breaking
  - title: 🚀 Features
    labels:
      - feature
      - enhancement
  - title: 🐛 Bug Fixes
    labels:
      - fix
      - bug
  - title: 🧰 Maintenance
    label:
      - chore
      - dependencies
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - major
      - breaking
  minor:
    labels:
      - minor
      - feature
      - enhancement
  patch:
    labels:
      - patch
      - dependencies
  default: patch
template: |
  ## What's Changed

  $CHANGES

  ## ⭐️ Contributors

  $CONTRIBUTORS

  ## Sponsorship

  If you like this project, please consider supporting me:

  - ☕️ [Buy Me A Coffee](https://buymeacoffee.com/jurkash)
  - 🤝 [Support on Patreon](https://patreon.com/jurkash)
